name: CI

on:
  push: { branches: [ "main" ] }
  pull_request:
  workflow_dispatch:

concurrency:
  # Run everything on main, most-recent on PR builds
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    container: graphcore/pytorch:3.2.0-ubuntu-20.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Install dev-requirements
      run: |
        apt-get update
        apt-get install -y git
        pip install -r requirements-dev.txt
    - name: Run CI
      run: ./dev ci
    - name: Publish docs
        if: ${{github.ref == 'refs/heads/main'}}
        uses: Cecilapp/GitHub-Pages-deploy@3.2.1
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        with:
          build_dir: docs/build/html